export const StreamData = [
  {
    course: "Biotechnology",
    color: "#B4AA91",
    id: 1,
    content: "Aims in the areas of healthcare & environment bridging Science & Engineering in Biology.",
    links: {
      sem1: "https://drive.google.com/folderview?id=1nsHApn3Rlaq1R76Qnga_hXigGZtoQgAe",
      sem2: "https://drive.google.com/folderview?id=1znI96LQZIsZY5ZZH6oOttagjez6mHVvU",
      sem3: "https://drive.google.com/folderview?id=1V5NANXVWJSj2Nz03e41ahoSzAxOLWCXP",
      sem4: "https://drive.google.com/drive/folders/1p9a6D6o6wnUQ1f6s75-WRl14T8ReoiwD?usp=sharing",
      sem5: "https://drive.google.com/drive/folders/1p9a6D6o6wnUQ1f6s75-WRl14T8ReoiwD?usp=sharing",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Civil Engineering",
    color: "#7A4930",
    id: 2,
    content: "Deals with the design, construction, and maintenance of the physical and naturally built environment.",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Computer Engineering",
    color: "#603060",
    id: 3,
    content: "In-depth knowledge of computation, programming languages & integrates fields of CS.",
    links: {
      sem1: "https://drive.google.com/drive/folders/1Hq4f3N4apF5fY70_3E3l2rpyCX_KereI?usp=sharing",
      sem2: "https://drive.google.com/drive/folders/1t5YSmqO2BCM-cd6Dk06GNMCKgRvlnY3X",
      sem3: "https://drive.google.com/drive/folders/1zaHAbQyz11vYSWWTPKpJ2jLFLDsNrKSm?usp=sharing",
      sem4: "https://drive.google.com/drive/folders/1cEPXqPaPizTG9MJXWcifWyaVpg3Tf32Z",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "CSAI",
    color: "#658539",
    id: 4,
    content: "Understanding of foundational topics in Computer Science, Artificial Intelligence, & ML.",
    links: {
      sem1: "https://drive.google.com/drive/folders/14j36nCdzmwqr7EeP9Iy040NBtrN3-wMu?usp=shari",
      sem2: "https://drive.google.com/drive/folders/1t5YSmqO2BCM-cd6Dk06GNMCKgRvlnY3X",
      sem3: "https://drive.google.com/drive/folders/1zaHAbQyz11vYSWWTPKpJ2jLFLDsNrKSm?usp=sharing",
      sem4: "https://drive.google.com/drive/folders/1cEPXqPaPizTG9MJXWcifWyaVpg3Tf32Z",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "CSDS",
    color: "#705E1E",
    id: 5,
    content: "Understanding of foundations, limits, and capabilities of computing.",
    links: {
      sem1: "https://drive.google.com/drive/mobile/folders/14j36nCdzmwqr7EeP9Iy040NBtrN3-wMu?usp=sharing",
      sem2: "https://drive.google.com/drive/folders/1t5YSmqO2BCM-cd6Dk06GNMCKgRvlnY3X",
      sem3: "https://drive.google.com/drive/folders/1zaHAbQyz11vYSWWTPKpJ2jLFLDsNrKSm?usp=sharing",
      sem4: "https://drive.google.com/drive/folders/1cEPXqPaPizTG9MJXWcifWyaVpg3Tf32Z",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "ECE",
    color: "#725D64",
    id: 6,
    content: "Provides a perspective of the field of electronics and allows students to decide future directions.",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "ECAM",
    color: "#939894",
    id: 7,
    content: "Branch includes ECE with edge knowledge of AI-ML techniques.",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Electrical Engineering",
    color: "#009C8B",
    id: 8,
    content: "Practical applications of electricity in all its forms, including those of the field of electronics.",
    links: {
      sem1: "https://drive.google.com/drive/folders/1MLcj0zTXGB6oTKxTCyXzY5gFCubHyoiG?usp=sharing",
      sem2: "https://drive.google.com/drive/folders/1Hq4f3N4apF5fY70_3E3l2rpyCX_KereI",
      sem3: "https://drive.google.com/drive/folders/1sdTVGM7rH7zS6neriYmtzDLuT9--fpRj?usp=sharing",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "EIOT",
    color: "#DB2E0F",
    id: 7,
    content: "Develops innovative services that help users to receive, control & manage information.",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Geoinformatics",
    color: "#B06010",
    id: 8,
    content: "Combines fields of geography, geosciences & related branches of science & engineering.",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Instrument & Control Engineering",
    color: "#2C63A0",
    id: 8,
    content: "Study of measurement, control & implementation of process variables in systems.",
    links: {
      sem1: "https://drive.google.com/drive/folders/1MLcj0zTXGB6oTKxTCyXzY5gFCubHyoiG?usp=sharing",
      sem2: "https://drive.google.com/drive/folders/1Hq4f3N4apF5fY70_3E3l2rpyCX_KereI",
      sem3: "https://drive.google.com/drive/folders/1l8DIO2qPtse90hA0HFYNJHzG86BF_S1i?usp=sharing",
      sem4: "https://drive.google.com/drive/folders/1w2_sWHJeaveeEU6SAFJ6HlH6WhYF5FbW",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Information Technology",
    color: "#9A9C43",
    id: 8,
    content: "In-depth knowledge of DSA, databases, networks, IoT, ML.",
    links: {
      sem1: "https://drive.google.com/drive/folders/1Hq4f3N4apF5fY70_3E3l2rpyCX_KereI?usp=sharing",
      sem2: "https://drive.google.com/drive/folders/1t5YSmqO2BCM-cd6Dk06GNMCKgRvlnY3X",
      sem3: "https://drive.google.com/drive/folders/1eiH67BKsrP8kXNjf9ABo3fEwsPneiQmk?usp=sharing",
      sem4: "https://drive.google.com/drive/folders/1cEPXqPaPizTG9MJXWcifWyaVpg3Tf32Z",
      sem5: "https://drive.google.com/drive/folders/1eMz9CrhqJO_OE-NQgSti7Jlg2UePCgPF?usp=sharing",
      sem6: "https://drive.google.com/drive/folders/1KGfXwIklt3KoNIBnIWP3yV4PfbUCGZgM?usp=sharing",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Mathematics & Computing",
    color: "#3a485f",
    id: 8,
    content: "Study & analysis of abstract concepts, such as numbers & patterns.",
    links: {
      sem1: "https://drive.google.com/drive/folders/1Hq4f3N4apF5fY70_3E3l2rpyCX_KereI?usp=sharing",
      sem2: "https://drive.google.com/drive/folders/1t5YSmqO2BCM-cd6Dk06GNMCKgRvlnY3X",
      sem3: "https://drive.google.com/drive/folders/1ezH5HZGpR_34FCCTdI1RpRkyXcHxROqu?usp=sharing",
      sem4: "https://drive.google.com/drive/folders/1K6jV-ItFP2q20VIwdx8P018k5bTLlO2v?usp=sharing",
      sem5: "https://drive.google.com/folderview?id=1MvaQjJR9FUzyUfC-spbNeskAny7d-Df-",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Mechanical Engineering",
    color: "#4e3e5b",
    id: 8,
    content: "Combines engineering physics & mathematics principles with materials science",
    links: {
      sem1: "https://drive.google.com/drive/folders/1MLcj0zTXGB6oTKxTCyXzY5gFCubHyoiG?usp=sharing",
      sem2: "https://drive.google.com/folderview?id=1t5YSmqO2BCM-cd6Dk06GNMCKgRvlnY3X",
      sem3: "https://drive.google.com/folderview?id=1I7c7APn3g_VMPizem5fDy9OWMf_GKyCA",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "MPAE",
    color: "#0b575b",
    id: 8,
    content: "Deals with the concepts & processes involved in the design & development of machines.",
    links: {
      sem1: "https://drive.google.com/drive/folders/1MLcj0zTXGB6oTKxTCyXzY5gFCubHyoiG?usp=sharing",
      sem2: "https://drive.google.com/folderview?id=141dMNfrlr5hS2f0JQ-q_GV9NPVCE1ezO",
      sem3: "https://drive.google.com/folderview?id=1-w7N9qj3VPDRGIWSSqPypKMMnVUtCCgr",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
];
