export const StreamData = [
  {
    course: "Information Technology",
    color: "#B4AA91",
    id: 1,
    content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "COE",
    color: "#7A4930",
    id: 2,
    content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "ECE",
    color: "#603060",
    id: 3,
    content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Information Technology",
    color: "#658539",
    id: 4,
    content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Information Technology",
    color: "#705E1E",
    id: 5,
    content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Information Technology",
    color: "#725D64",
    id: 6,
    content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Information Technology",
    color: "#939894",
    id: 7,
    content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Information Technology",
    color: "#009C8B",
    id: 8,
    content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
];
